[package]
name = "iridium_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iridium_ecs = { path = "../iridium_ecs" }
iridium_ecs_macros = { path = "../iridium_ecs_macros" }
winit = "0.26.1"
env_logger = "0.9.0"
wgpu = "0.12"
tokio = { version = "1.18.2", features = ["full"] }
hashbrown = "0.12.1"
