[package]
name = "iridium_collision"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iridium_ecs = { path = "../iridium_ecs" }
iridium_maths = { path = "../iridium_maths" }

egui = "0.19.0"
