[package]
name = "iridium_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iridium_graphics = { path = "../iridium_graphics" }
hashbrown = "0.12.1"
